- hosts: all
  gather_facts: no
  sudo: true
  vars:
    #aws_bootstrap_aws_access_key: ""
    #aws_bootstrap_aws_secret_key: ""
    #aws_bootstrap_aws_account_id: ""

    # Server Keys
    aws_bootstrap_aws_keypair_name: keypair-name-2015
    aws_bootstrap_aws_private_key: ~/.ssh/aws-keypair-private-key.pem

    #Deploy Keyfile
    github_deploy_key: deploy_key
    github_local_deploy_key: ~/.ssh/deploy_key
    
    vpc_name: my-vpc-name
    domain: example.com
    github_repo: github_username
    safe_cidr: "65.200.54.234/32"
    
    # Region
    aws_bootstrap_aws_region: us-west-2
    aws_bootstrap_aws_zone: "{{ aws_bootstrap_aws_region }}a"
    aws_bootstrap_aws_zone_alt: "{{ aws_bootstrap_aws_region }}b"

  roles:
    - role: aws_bootstrap
      aws_bootstrap_terraform_file: vpc.tf
      aws_bootstrap_vpc_name: "{{ vpc_name }}"
      aws_bootstrap_state_bucket: state.provision.{{ domain }}
      aws_bootstrap_jump_access_cidr: "{{ safe_cidr }}"
      aws_bootstrap_state_file: genesis.tfstate

      aws_bootstrap_playbook_repo: "ssh://git@github.com/{{github_repo}}/ansible-playbook"
      aws_bootstrap_playbook_repo_version: master
      aws_bootstrap_playbook_repo_keyfile: "{{ github_deploy_key }}"
      aws_bootstrap_terraform_repo: "ssh://git@github.com/{{github_repo}}/aws-site"
      aws_bootstrap_terraform_repo_version: master
      aws_bootstrap_terraform_repo_keyfile: "{{ github_deploy_key }}"
      aws_bootstrap_keys:
        - "{{ github_local_deploy_key }}"
        - "{{ aws_bootstrap_aws_private_key }}"

