---

- name: common - create bootstrap folder
  file:
    state=directory
    path={{ aws_bootstrap_deploy_dir }}/
    mode=770

- name: common - ensure .gitignore exists
  file:
    state=touch
    path={{ aws_bootstrap_deploy_dir }}/../.gitignore

- name: common - ensure .gitignore is correct
  lineinfile: 
    dest={{ aws_bootstrap_deploy_dir }}/../.gitignore
    line={{ item }}
  with_items:
    - "**/terraform.tfvars"
    - "**/bootstrap"
    - "**/destroy"
    - "**/provision/**"

- name: common - move setup files
  copy:
    src=provision/
    dest={{ aws_bootstrap_deploy_dir }}/
    mode=660

- name: common - generate terraform tfvars file
  template:
    src=vpc-genesis.tfvars.j2
    dest={{ aws_bootstrap_deploy_dir }}/vpc-genesis.tf
    mode=660

- name: common - generate terraform tfvars file
  template:
    src=terraform.tfvars.j2
    dest={{ aws_bootstrap_deploy_dir }}/terraform.tfvars
    mode=660

- name: common - provision.yml
  template:
    src=provision.yml.j2
    dest={{ aws_bootstrap_deploy_dir }}/provision.yml
    mode=660

- name: common - generate bootstrap file
  template:
    src=bootstrap.j2
    dest={{ aws_bootstrap_deploy_dir }}/bootstrap
    mode=750

- name: common - generate destroy file
  template:
    src=destroy.j2
    dest={{ aws_bootstrap_deploy_dir }}/destroy
    mode=750

- name: common - copy terraform modle file
  copy:
    src={{ aws_bootstrap_terraform_file }}
    dest={{ aws_bootstrap_deploy_dir }}/vpc-genesis.tf
    mode=640
  when: {{ aws_bootstrap_terraform_file|length > 0 }}

