---

- name: create - check for existence of bucket state file
  s3:
    bucket={{ aws_bootstrap_state_bucket }}
    mode=get
    object={{ aws_bootstrap_state_file }}
    aws_access_key={{ aws_access_key }}
    aws_secret_key={{ aws_secret_key }}
    region={{ aws_region }}
  ignore_errors: yes
  register: state_file

- name: create - do terraform module update 
  shell: terraform get -update
  args:
    chdir: "{{ aws_bootstrap_deploy_dir }}/"

- name: create - do a test on the plan
  shell: terraform plan -module-depth=-1
  args:
    chdir: "{{ aws_bootstrap_deploy_dir }}/"
  when: state_file.failed
  register: tf_run

- debug: var=tf_run

