
- src: https://github.com/gotansible/basics
  name: gotansible.basics

- src: https://github.com/gotansible/terraform
  name: gotansible.terraform

- src: https://github.com/gotansible/gobuild
  name: gotansible.gobuild

- src: https://github.com/gotansible/sshkey
  name: gotansible.sshkey

- src: https://github.com/gotansible/aws-credentials
  name: gotansible.sshkey

- src: https://github.com/gotansible/aws-provision
  name: gotansible.aws-provision


